backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "profile"
    label: "Profile"
    files:
      - file: "content/profile/profile.md"
        label: "Profile Info"
        name: "profile"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Bio", name: "bio", widget: "text" }
          - { label: "Avatar", name: "avatar", widget: "image" }

  - name: "projects"
    label: "Projects"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Demo Link", name: "demo", widget: "string" }
      - { label: "Code Link", name: "code", widget: "string" }
